info.project:
  name: Initializer Service

server.port: 8400

spring:
  application.name: initializer

initializer:
  services:
    github:
      token: <https://github.com/settings/tokens>
      organization: Byzaneo

byzaneo:
  billing.enabled: false
