info.project:
  name: Initializer Service

server.port: 8400

spring:
  application.name: initializer

initializer:
  github:
    token: <https://github.com/settings/tokens>
    organization: Byzaneo
  docker:
    registry: repository.byzaneo.com
    username: byzaneo.io
    password: [PASSWORD]
  travis:
    api: https://api.travis-ci.com/
    token: [TOKEN]

byzaneo:
  billing.enabled: false
