language: {{#lowercase}}{{project.language.name}}{{/lowercase}}
{{#el}}language.name eq 'Java' ?  'jdk: openjdk' + language.version : ''{{/el}}
sudo: required
{{#el}}
assembly.name eq 'Docker'
?
'services:
  - docker
'
: ''
{{/el}}
{{#el}}
management.name eq 'Maven'
?
'cache:
  directories:
    - "$HOME/.m2/repository"
'
: ''
{{/el}}

env:
  global:
    - PROJECT_NAME={{project.name}}
{{#el}}
assembly.name eq 'Docker'
?
'    - TAG=latest
    - IMAGE_NAME=' + assembly.registry + '/' + name + '
'
: ''
{{/el}}

install: true

script:
  - ./target/travis-script.sh
after_success:
  - ./target/travis-success.sh

before_deploy:
  - ./target/travis-pre-deploy.sh
deploy:
  provider: script
  script: "./target/travis-deploy.sh"
  on:
    branch: master