language: {{#lowercase}}{{project.language.id}}{{/lowercase}}
{{#facets.Java}}
jdk: openjdk{{project.language.version}}
{{/facets.Java}}
sudo: required
{{#facets.Docker}}
services:
  - docker
{{/facets.Docker}}
{{#facets.Maven}}
cache:
  directories:
    - "$HOME/.m2/repository"
{{/facets.Maven}}

env:
  global:
{{#facets.Docker}}
    - TAG=latest
    - IMAGE_NAME=$REGISTRY_HOSTNAME/$PROJECT_NAME
{{/facets.Docker}}

install: true

script:
{{#facets.Maven}}
  - mvn package -U -B -P prod,coverage
{{/facets.Maven}}

{{#facets.CodeCov}}
after_success:
  - bash <(curl -s https://codecov.io/bash)
{{/facets.CodeCov}}

{{#facets.Docker}}
before_deploy:
  - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_HOSTNAME
  - docker pull "$IMAGE_NAME" || true
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
  - docker images
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TAG}"
{{/facets.Docker}}
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x deploy.sh && ./deploy.sh
  on:
    branch: master