language: {{#lowercase}}{{project.language.id}}{{/lowercase}}
{{#facets.Java}}
jdk: openjdk{{project.language.version}}
{{/facets.Java}}
sudo: required
{{#facets.Docker}}
services:
  - docker
{{/facets.Docker}}
{{#facets.Maven}}
cache:
  directories:
    - "$HOME/.m2/repository"
{{/facets.Maven}}

install: true

script:
{{#facets.Maven}}
  - mvn package -U -B -P prod,coverage
{{/facets.Maven}}

{{#facets.CodeCov}}
after_success:
  - bash <(curl -s https://codecov.io/bash)
{{/facets.CodeCov}}

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x deploy.sh && ./deploy.sh
  on:
    branch: master